# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askApp', '0002_dangeralert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dangeralert',
            old_name='alert_latitude',
            new_name='alert_address',
        ),
        migrations.RemoveField(
            model_name='dangeralert',
            name='alert_longitude',
        ),
    ]
