# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askApp', '0003_auto_20171119_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangeralert',
            name='alert_attended_to',
            field=models.BooleanField(default=False),
        ),
    ]
