# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('askApp', '0004_dangeralert_alert_attended_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangeralert',
            name='alert_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
